//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFNET_Portal {
    
    
    public partial class wbm_Selecc {
        
        /// <summary>
        /// Selecc_ddl_Instancia_m control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Selecc_ddl_Instancia_m;
        
        /// <summary>
        /// Selecc_ddl_Seccion_m control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Selecc_ddl_Seccion_m;
        
        /// <summary>
        /// Selecc_ddl_Proyecto_m control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Selecc_ddl_Proyecto_m;
        
        /// <summary>
        /// Selecc_ddl_Proyectobod_m control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Selecc_ddl_Proyectobod_m;
        
        /// <summary>
        /// Selecc_ddl_Bodega_m control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Selecc_ddl_Bodega_m;
    }
}
